# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9
      - name: pnpm install
        uses: jjs98/pnpm-install-action@v6
      - name: Eslint Annotate
        uses: a-b-r-o-w-n/eslint-action@v2.2.0
