# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9
          run_install: false
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: eslint . -c .eslintrc.cjs --ext .ts,.js,.cjs,.vue,.tsx,.jsx -o lint_report.json -f json || true
      - name: show errors
        run: cat lint_report.json
      - name: Annotate Action
        # You may pin to the exact commit or the version.
        # uses: yuzutech/annotations-action@0e061a6e3ac848299310b6429b60d67cafd4e7f8
        uses: yuzutech/annotations-action@v0.5.0
        with:
          # Token used to interact with the GitHub API.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Path to a JSON file which contains a list of annotations.
          input: lint_report.json
          # Title of the check
          # title: # optional, default is check
          # # Ignore errors when the provided repo-token does not have write permissions
          # ignore-unauthorized-error: # optional, default is false
          # # Ignore if the file which contains annotations is missing
          # ignore-missing-file: # optional, default is true
      
      
      
